"""Add source info for location.

Revision ID: 10d568cd0cae
Revises: ef7908667f5f
Create Date: 2025-05-22 23:48:19.756703

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "10d568cd0cae"
down_revision = "ef7908667f5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("location", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("source", sa.String(length=50), nullable=True))
        batch_op.add_column(
            sa.Column("source_id", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))
        batch_op.alter_column(
            "place_name", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.drop_column("accuracy")
        batch_op.drop_column("altitude")
        batch_op.drop_column("timestamp")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("location", schema=None) as batch_op:
        batch_op.add_column(sa.Column("timestamp", sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column("altitude", sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column("accuracy", sa.FLOAT(), nullable=True))
        batch_op.alter_column(
            "place_name", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.drop_column("created_at")
        batch_op.drop_column("source_id")
        batch_op.drop_column("source")
        batch_op.drop_column("category")

    # ### end Alembic commands ###
