"""Add GPS positions.

Revision ID: 8533291ff46b
Revises: f76535475ba2
Create Date: 2025-05-08 11:39:53.967515

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8533291ff46b"
down_revision = "f76535475ba2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gps_position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("altitude", sa.Float(), nullable=True),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.Column("bearing", sa.Float(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("gps_position", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gps_position_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gps_position", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gps_position_timestamp"))

    op.drop_table("gps_position")
    # ### end Alembic commands ###
