"""Switch to hashed passwords

Revision ID: cd83646a4136
Revises: a3fb8091f808
Create Date: 2024-12-18 21:06:13.729188

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd83646a4136"
down_revision = "a3fb8091f808"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_hash", sa.String(length=128), nullable=False)
        )
        batch_op.drop_column("password")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password", sa.VARCHAR(length=128), nullable=False)
        )
        batch_op.drop_column("password_hash")

    # ### end Alembic commands ###
