"""Add event notes.

Revision ID: f76535475ba2
Revises: 46e923572cb7
Create Date: 2025-05-08 00:11:49.742065

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f76535475ba2"
down_revision = "46e923572cb7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.add_column(sa.Column("notes", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_column("notes")

    # ### end Alembic commands ###
